name: lint
on:
  push:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: pylint --exit-zero *.py
